DROP DATABASE IF EXISTS court_tracking_system;
CREATE DATABASE court_tracking_system;
USE court_tracking_system;

DROP TABLE IF EXISTS Charge;
DROP TABLE IF EXISTS CaseRecord;
DROP TABLE IF EXISTS Defendant;
DROP TABLE IF EXISTS Lawyer;
DROP TABLE IF EXISTS Case_Lawyer;
DROP TABLE IF EXISTS Court_Event;

CREATE TABLE Defendant (
    Defendant_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Date_of_Birth DATE NOT NULL,
    Address TEXT,
    Ethnicity VARCHAR(255),
    Phone_Number VARCHAR(15),
    Email VARCHAR(255),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CaseRecord (
    Case_ID INT AUTO_INCREMENT PRIMARY KEY,
    Defendant_ID INT NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Defendant_ID) REFERENCES Defendant(Defendant_ID) ON DELETE CASCADE
);

CREATE TABLE Charge (
    Charge_ID INT AUTO_INCREMENT PRIMARY KEY,
    Case_ID INT NOT NULL,
    Description TEXT,
    Status VARCHAR(50),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Case_ID) REFERENCES CaseRecord(Case_ID) ON DELETE CASCADE
);

CREATE TABLE Lawyer (
    Lawyer_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255),
    Phone_Number VARCHAR(15),
    Firm VARCHAR(255),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Case_Lawyer (
    Case_ID INT NOT NULL,
    Lawyer_ID INT NOT NULL,
    PRIMARY KEY (Case_ID, Lawyer_ID),
    FOREIGN KEY (Case_ID) REFERENCES CaseRecord(Case_ID) ON DELETE CASCADE,
    FOREIGN KEY (Lawyer_ID) REFERENCES Lawyer(Lawyer_ID) ON DELETE CASCADE
);

CREATE TABLE Court_Event (
    Event_ID INT AUTO_INCREMENT PRIMARY KEY,
    Case_ID INT NOT NULL,
    Location VARCHAR(255),
    Description VARCHAR(255),
    Date DATE,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Case_ID) REFERENCES CaseRecord(Case_ID) ON DELETE CASCADE
);