<a href="<?= BASE_URL ?>/" class="btn btn-outline-secondary mb-3">← Back</a>

<?php if (!empty($_GET['success'])): ?>
  <div class="alert alert-success"><?= htmlspecialchars($_GET['success']) ?></div>
<?php endif; ?>

<!-- card layout generated by ChatGPT --> 
<div class="row my-5 justify-content-center">
  <div class="col-md-10">
    <div class="card mb-4 shadow-sm rounded-3">
      <div class="row g-0 align-items-center">
        <div class="col-md-8 p-4">
          <h4 class="card-title">Manage Existing Defendents</h4>
          <p class="card-text text-muted">
            Access and update defendents already in the system, review details, and make changes as needed.
          </p>
        </div>
        <div class="col-md-4 text-end pe-4">
          <a href="<?= BASE_URL ?>/defendant/manage" class="btn btn-outline-primary btn-lg">Manage Defendants</a>
        </div>
      </div>
    </div>

    <div class="card shadow-sm rounded-3">
      <div class="row g-0 align-items-center">
        <div class="col-md-8 p-4">
          <h4 class="card-title">Add New Defendent</h4>
          <p class="card-text text-muted">
            Create a new defendent by entering personal details. 
          </p>
        </div>
        <div class="col-md-4 text-end pe-4">
          <a href="<?= BASE_URL ?>/defendant/add" class="btn btn-primary btn-lg">Add Defendant</a>
        </div>
      </div>
    </div>
  </div>
</div>
