<!-- card layout generated by ChatGPT --> 
<a href="<?= BASE_URL ?>/" class="btn btn-outline-secondary">← Back</a>

<div class="row my-5 justify-content-center">
  <div class="col-md-10">
    <div class="card mb-4 shadow-sm rounded-3">
      <div class="row g-0 align-items-center">
        <div class="col-md-8 p-4">
          <h4 class="card-title">Manage Existing Cases</h4>
          <p class="card-text text-muted">
            Access and update cases already in the system, review details, and make changes as needed.
          </p>
        </div>
        <div class="col-md-4 text-end pe-4">
          <a href="<?= BASE_URL ?>/case/manage" class="btn btn-outline-primary btn-lg">Manage Cases</a>
        </div>
      </div>
    </div>

    <div class="card shadow-sm rounded-3">
      <div class="row g-0 align-items-center">
        <div class="col-md-8 p-4">
          <h4 class="card-title">Add New Case</h4>
          <p class="card-text text-muted">
            Begin a new case by entering details for the defendant, lawyer, charges, and court events.
          </p>
        </div>
        <div class="col-md-4 text-end pe-4">
          <a href="<?= BASE_URL ?>/case/defendant" class="btn btn-primary btn-lg">Add Case</a>
        </div>
      </div>
    </div>
  </div>
</div>
