-- PLEASE NOTE: Seed data script has been generated by ChatGPT's GPT-4o-mini model

USE court_tracking_system;

-- Insert into defendant table
INSERT INTO defendant (Name, Date_of_Birth, Address, Ethnicity, Phone_Number, Email)
VALUES 
('John Doe', '1985-04-12', '123 Main Street, Sydney', 'Caucasian', '0412345678', 'john.doe@example.com'),
('Jane Smith', '1990-07-23', '456 Elm Street, Melbourne', 'Asian', '0498765432', 'jane.smith@example.com'),
('Michael Johnson', '1978-11-02', '789 Oak Avenue, Brisbane', 'African Australian', '0423456789', 'michael.johnson@example.com');

-- Insert into caserecord table
INSERT INTO caserecord (defendant_ID)
VALUES 
(1),
(2),
(3);

-- Insert into charge table
INSERT INTO charge (Case_ID, Description, Status)
VALUES
(1, 'Theft under $5000', 'Pending'),
(1, 'Resisting Arrest', 'Pending'),
(2, 'Assault Occasioning Actual Bodily Harm', 'Closed'),
(3, 'Fraudulent Misrepresentation', 'Open');

-- Insert into Lawyer table
INSERT INTO Lawyer (Name, Email, Phone_Number, Firm)
VALUES 
('Richard Roe', 'richard.roe@example.com', '0411223344', 'Roe & Co. Law Firm'),
('Lisa White', 'lisa.white@example.com', '0433344556', 'White Legal Group'),
('David Brown', 'david.brown@example.com', '0422334455', 'Brown & Brown Lawyers');

-- Insert into case_lawyer table
INSERT INTO case_lawyer (Case_ID, Lawyer_ID)
VALUES 
(1, 1),
(2, 2),
(3, 3);

-- Insert into court_event table
INSERT INTO court_event (Case_ID, Location, Description, Date)
VALUES 
(1, 'Sydney Courtroom 1', 'Preliminary hearing for theft and resisting arrest', '2025-05-10'),
(2, 'Melbourne Courtroom 3', 'Trial for assault occasioning actual bodily harm', '2025-06-15'),
(3, 'Brisbane Courtroom 2', 'Hearing for fraudulent misrepresentation', '2025-07-20');

-- Test admin user for login
INSERT INTO users (username, password, role)
VALUES (
  'admin',
  '$2y$10$wrilxoWJHndvlTMYFlzb6ucrnHSIrn.tcgJWoleq3kaIgT0ILIZ7u',
  'admin'
);

